### ISSUE TITLE
Shared storage across containers

### ISSUE THREAD

**Issue by craig-willis** [nds-org/esiphub#8]
I am trying to created a "shared" directory for my workshop and am stuck. Here is what I'd like to do "in theory": mount a shared space (e.g. folder, drive, etc.) where all the workshop participants can see (read/write) the data in it.  The goal here is to actually have a single place for data that all participants will use and to also have a place for shared notebooks that are not pushed back up to Github. What's the fastest+best path to that solution?

**Comment by craig-willis** [comment]
The `rook` approach we're using for individual user data (ReadWriteOnce persistent volume claims) does not support shared volumes.  We've been exploring using rook's shared volume support, but have come to the conclusion that simple NFS is even better. @bodom0015  has written something up on a Wiki https://opensource.ncsa.illinois.edu/confluence/display/~lambert8/NFS+in+Kubernetes#NFSinKubernetes-BasicIn-ClusterServerExample

Based on this, we can update the jupyterhub config to mount the extra volume:

```
singleuser:
  memory:
    guarantee: 1G
    limit: 8G
  storage:
    type: dynamic
    capacity: 10Gi
    dynamic:
      storageClass: rook-block
    extraVolumeMounts:
      - name: nfs-share
        mountPath: /shared
    extraVolumes:
      - name: nfs-share
        nfs:
          server: "10.105.209.51"
          path: "/"
          readOnly: false
  image:
    name: ndslabs/esiphub-notebook
    tag: latest
```

We're using the service IP here because Kubernetes internal DNS isn't accessible from the host. Eventually we might resolve this by modifying the host [resolve.conf](https://github.com/kubernetes/kubernetes/issues/44528).
